### ISSUE TITLE
trapperkeeper augeas lens fails for ruby-load-path

### ISSUE THREAD

**Issue by mmckinst** [camptocamp/puppet-puppetserver#11]
See below for steps necessary to reproduce. The ruby-load-path should be formatted like """ruby-load-path: [/opt/puppetlabs/puppet/lib/ruby/vendor_ruby, /tmp]"""

```
[root@foo ~]# augtool -I /opt/puppetlabs/puppet/share/augeas/lenses/  -n set /files/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf/jruby-puppet/ruby-load-path/2 "/tmp"
Saved 1 file(s)
[root@foo ~]#
[root@foo ~]#
[root@foo ~]# diff -u /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf.augnew 
--- /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf	2015-06-15 11:20:46.737873717 -0400
+++ /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf.augnew	2015-06-15 14:41:29.743240989 -0400
@@ -2,7 +2,11 @@
 jruby-puppet: {
     # Where the puppet-agent dependency places puppet, facter, etc...
     # Puppet server expects to load Puppet from this location
-    ruby-load-path: [/opt/puppetlabs/puppet/lib/ruby/vendor_ruby]
+ruby-load-path:
+{
+1:/opt/puppetlabs/puppet/lib/ruby/vendor_ruby
+2:/tmp
+}
 
     # This setting determines where JRuby will look for gems.  It is also
     # used by the `puppetserver gem` command line tool.
@@ -47,6 +51,8 @@
 
 # Settings related to the puppet-admin HTTP API
 puppet-admin: {
-    client-whitelist: []
+client-whitelist:
+{
+}
 }
 
[root@foo ~]# 

```

**Comment by mmckinst** [comment]
changing ```let rec entry = hash (entry|simple|array)``` to ```let rec entry = hash (simple|array)``` will make it work correctly on ruby-load-path in puppetserver.conf but breaks with on ca.conf which has nested hashes so to say.

**Comment by poikilotherm** [comment]
Would this solve setting puppet-admin/client-whitelist to an array, too? Currently, this doesn't work (and I am really bad at writing lenses...)

**Comment by raphink** [comment]
@mmckinst @poikilotherm 

In order to fix #7 I just commited a big change that remaps the entire lens and types every entry.

Therefore, entries will now be typed as either `@hash` or `@array`, which should solve that issue, too. Let me know!

**Comment by raphink** [comment]
@mmckinst @poikilotherm can you confirm that releaes 2.0.0 fixes that issue?

**Comment by poikilotherm** [comment]
Hi @raphink, I will check on wednesday and report back as I attended a training for tomorrow.

**Comment by raphink** [comment]
Thank you @poikilotherm

**Comment by poikilotherm** [comment]
Hi @raphink ,

the lens still is not working correctly.

Test case 1:
```
puppetserver::config::puppetserver { 'puppetserver.conf/puppet-admin/client-whitelist':
   value => [$::fqdn]
}
```
Should result in
```
client-whitelist: [puppetmaster.fqdn.tld]
```
But results in
```
client-whitelist:puppetmaster.fqdn.tld
```
which breaks puppetserver.

Test case 2:
```
puppetserver::config::puppetserver { 'puppetserver.conf/puppet-admin/client-whitelist':
   value => [$::fqdn, 'localhost']
}
```
results in
```
client-whitelist:[puppetmaster.fqdn.tld,localhost]
```
which is not very nice (missing spaces for readability) but works ok.

The indentation is not working, too. It should look like:
```
puppet-admin: {
    client-whitelist:[puppetmaster.fqdn.tld,localhost]
}
```
but it looks like
```
puppet-admin: {
client-whitelist:[puppetmaster.fqdn.tld,localhost]
}
```

**Comment by raphink** [comment]
@poikilotherm You need to add `setting_type => array` to your `puppetserver::config::puppetserver` resource.

**Comment by poikilotherm** [comment]
Ups, I didn't see that in the docs. Adding the `setting_type` solves everything! Great!

I would really appreciate if the indentation issue could be fixed, too.

Thanks anyway :-)

**Comment by raphink** [comment]
The indentation cannot be fixed currently, due to a limitation of recursive lenses in Augeas. I could set a default indentation, but then all entries would be indented, which would be worse than none.
