### ISSUE TITLE
auth.conf not parsable by the trapperkeeper lens 

### ISSUE THREAD

**Issue by damoxc** [camptocamp/puppet-puppetserver#23]
Using the latest puppetserver, the auth.conf file can't be read or modified by the trapperkeeper lens. My knowledge of writing lens isn't great but I'm going to guess that this is due to the nested hashes inside the array `rules`.

```
Could not evaluate: Augeas didn't load /etc/puppetlabs/puppetserver/conf.d/auth.conf with Trapperkeeper.lns: Syntax error (line:3, character:10)
```

This is just using an unmodified auth.conf from the package.

**Comment by raphink** [comment]
`auth.conf` is not meant to be parsed with the `Trapperkeeper.lns` lens. It's not the same format at all. If you want to modify `auth.conf`, you need to the use `Puppet_Auth.lns` lens. I would actually recommend using the `puppet_auth` type from [augeasproviders_puppet](http://github.com/hercules-team/augeasproviders_puppet).

**Comment by damoxc** [comment]
This isn't the leacy Puppet auth.conf but the new auth.conf that uses Trapperkeeper authentication.

See https://docs.puppetlabs.com/puppetserver/latest/config_file_auth.html#aside-changes-to-authorization-in-puppet-server-220/

**Comment by damoxc** [comment]
Actually, just noticed PuppetLabs provide a module for managing it anyway, sorry!

**Comment by mvisonneau** [comment]
Got the same issue..! Had it with `webserver.conf` and `puppetserver.conf` as well. What is the module you're using @damoxc ?

**Comment by mvisonneau** [comment]
My bad `webserver.conf` and `puppetserver.conf` works fine..

**Comment by damoxc** [comment]
@mvisonneau There's a module for specifically `auth.conf`, https://forge.puppetlabs.com/puppetlabs/puppet_authorization and also a module for the file format, https://forge.puppetlabs.com/puppetlabs/hocon

**Comment by mvisonneau** [comment]
Cool, thanks for the info @damoxc !
