### ISSUE TITLE
how to configure puppet.conf

### ISSUE THREAD

**Issue by igalic** [camptocamp/puppet-puppetserver#4]
this module doesn't seem to be made to set any values in `/etc/puppet/puppet.conf`
@camptocamp's puppet-puppet doesn't seem to be made to work with this module :(

just managing the config with Ini_settings seems a bit off…

**Comment by mcanevet** [comment]
@igalic we are actually using theforeman-puppet to configure puppet.conf. I'm not sur it in the scope of this module to manage this file.
