### ISSUE TITLE
undocumented dependency: camptocamp/agueas

### ISSUE THREAD

**Issue by trosine** [camptocamp/puppet-puppetserver#6]
After installing and configuring my nodes to use this module, I received errors because it couldn't load the augeas class referred to in puppetserver::config::puppetserver.

**Comment by raphink** [comment]
You're right, the dependency is missing in metadata.json. We'll need to fix that.

**Comment by raphink** [comment]
@mmckinst I see you've made a commit for this. Can you open an PR please?
