### ISSUE TITLE
Trapperkeeper lens fails web-routes.conf

### ISSUE THREAD

**Issue by trosine** [camptocamp/puppet-puppetserver#7]
The standard content of `/etc/puppetserver/conf.d/web-routes.conf` includes complex keys that are not currently supported by the lens. After some troubleshooting, I've narrowed down some use cases to the special case of using keys with "/" which needs to be double quoted.

Even though I don't change web-routes.conf, this results a warning for every configuration entry I make using this module.

```
test: {
  "x" : z
  "x/y" : z
}```

**Comment by raphink** [comment]
Supporting quotes in keys might be doable. However, it won't be possible to have `/` in keys, so that would require a non backwards-compatible change, where keys are mapped as node values.

**Comment by raphink** [comment]
This should be fixed now. Beware that it changes the `setting` argument of `puppetserver::config::helper`!
